{% set name = "titrate" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/titrate-{{ version }}.tar.gz
  sha256: ba5bc6303b8869ca5078e99386826cfa2584d71f6363a87c950e0468a908157e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - numpy
    - scipy
    - matplotlib-base
    - gammapy
    - joblib

test:
  imports:
    - titrate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/StFroese/TITRATE
  summary: asympTotic lIkelihood Tests for daRk mAtTer sEarch
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - StFroese
